pdf_doc.cpp: add missing string literal
Resolves:

pdf_doc.cpp:529:16: error: format not a string literal and no format arguments [-Werror=format-security]
  529 |     fprintf(f, binary);